# Legacy makefile for building with MinGW
# It is included from MakeFiles/mingw32/Makefile

ifeq ($(DEBUG),0)
    smapi_CFLAGS := -O3 -Wall -funsigned-char -I$(smapi_HDIR)
else
    smapi_CFLAGS := -g -O2 -Wall -funsigned-char -I$(smapi_HDIR)
endif

smapi_CC := gcc
smapi_CDEFS :=
OBJ := .o

smapi_OBJS := api_jam$(OBJ) \
          api_sdm$(OBJ) \
          date2bin$(OBJ) \
          dosdate$(OBJ) \
          fexist$(OBJ) \
          ffind$(OBJ) \
          flush$(OBJ) \
          ftnaddr$(OBJ) \
          genmsgid$(OBJ) \
          locking$(OBJ) \
          memory$(OBJ) \
          months$(OBJ) \
          msgapi$(OBJ) \
          parsenn$(OBJ) \
          patmat$(OBJ) \
          qksort$(OBJ) \
          setfsize$(OBJ) \
          sq_area$(OBJ) \
          sq_hash$(OBJ) \
          sq_help$(OBJ) \
          sq_idx$(OBJ) \
          sq_kill$(OBJ) \
          sq_lock$(OBJ) \
          sq_misc$(OBJ) \
          sq_msg$(OBJ) \
          sq_read$(OBJ) \
          sq_uid$(OBJ) \
          sq_write$(OBJ) \
          strext$(OBJ) \
          strftim$(OBJ) \
          structrw$(OBJ) \
          tdelay$(OBJ) \
          trail$(OBJ) \
          weekday$(OBJ)

$(smapi_OBJS): %.o: $(smapi_SRCDIR)/%.c
	$(smapi_CC) $(smapi_CFLAGS) $(smapi_CDEFS) -c $(smapi_SRCDIR)/$*.c
